### PR TITLE
fix(scripts): support OSMO control-plane deploys with in-cluster Redis

### LINKED ISSUE #316: fix(scripts): OSMO control-plane deploy fails when using in-cluster Redis without managed Redis
### Component

OSMO Control Plane (Helm/Kubernetes)

### Bug Description

Deploying the OSMO control plane with `--use-incluster-redis` fails when the infrastructure was provisioned with managed Redis disabled. The failure is not caused by Terraform provisioning itself. The setup flow assumes external-Redis and workload-identity secret behavior even when the deployment explicitly requests in-cluster Redis.

During repro, the setup path failed across multiple stages:

- the shared helper resolved the SecretProviderClass manifest from an invalid path
- the workload-identity SecretProviderClass still requested the Key Vault secret for managed Redis
- the Helm chart expected `redis-secret` even for the in-cluster Redis path
- the chart rendered an empty Redis `storageClassName`, leaving the PVC unbound on the target cluster
- the post-deploy dev-user bootstrap step failed even though `osmo login` itself worked

### Steps to Reproduce

1. Provision infrastructure with a sanitized configuration equivalent to the snippet below, where PostgreSQL is enabled and managed Redis is disabled.
2. Run the setup deploy for the OSMO control plane with the in-cluster Redis option.
3. Observe the setup failure and the control-plane pods not reaching a healthy state.

Commands Used:

```bash
cd infrastructure/terraform
terraform init
terraform apply -var-file=<sanitized>.tfvars

cd ../setup
./03-deploy-osmo-control-plane.sh --use-incluster-redis
```

### Expected Behavior

The deploy script should complete successfully when Terraform does not provision managed Redis and the operator explicitly requests `--use-incluster-redis`. The control-plane should install with in-cluster Redis, all pods should become `Running`, and the post-deploy configuration step should not fail on optional dev-user management behavior.

### Environment

_No response_

### Logs / Error Output

```shell
/workspace/.../infrastructure/setup/manifests/aks-secret-provider-class.yaml: No such file or directory
error: no objects passed to apply

failed to get objectType:secret, objectName:redis-primary-key
RESPONSE 404: 404 Not Found
ERROR CODE: SecretNotFound

Error: secret "redis-secret" not found

FailedBinding: no persistent volumes available for this claim and no storage class is set

Server responded with status code 404
Error message: {"detail":"Not Found"}


Relevant Configuration:

Sanitized `terraform.tfvars` excerpt used for reproduction:


environment     = "<env>"
location        = "<azure-region>"
resource_prefix = "<resource-prefix>"
instance        = "<instance>"

should_create_resource_group = true

system_node_pool_vm_size    = "<system-node-vm-size>"
system_node_pool_node_count = 1

node_pools = {
  gpu = {
    vm_size                 = "<gpu-vm-size>"
    subnet_address_prefixes = ["<gpu-subnet-cidr>"]
    node_taints             = ["nvidia.com/gpu:NoSchedule", "kubernetes.azure.com/scalesetpriority=spot:NoSchedule"]
    gpu_driver              = "Install"
    node_labels = {
      "kubernetes.azure.com/scalesetpriority" = "spot"
    }
    priority                   = "Spot"
    should_enable_auto_scaling = true
    enable_auto_scaling        = true
    min_count                  = 0
    max_count                  = 1
    zones                      = []
    eviction_policy            = "Delete"
  }
}

should_deploy_postgresql = true
should_deploy_redis      = false

should_enable_private_endpoint    = true
should_enable_private_aks_cluster = true

should_enable_public_network_access     = false
should_add_current_user_key_vault_admin = true
should_enable_microsoft_defender        = true

should_deploy_grafana = false

osmo_config = {
  should_enable_identity   = true
  should_federate_identity = true
  control_plane_namespace  = "osmo-control-plane"
  operator_namespace       = "osmo-operator"
  workflows_namespace      = "osmo-workflows"
}
```

### Checklist

- [x] I have searched existing issues for duplicates
- [x] I have read the [documentation](README.md)

### PR DESCRIPTION
**Pull request by fbeltrao**
## Description

Fix the OSMO control-plane setup path so `./03-deploy-osmo-control-plane.sh --use-incluster-redis` works when Terraform is applied with managed Redis disabled.

This change:

- fixes the shared manifest path resolution for the Key Vault SecretProviderClass helper
- splits SecretProviderClass rendering so managed-Redis secrets are only requested when the deployment is actually using external Redis
- creates the `redis-secret` object expected by the `osmo/service` chart in the in-cluster Redis path
- detects a default Kubernetes `StorageClass` and passes it to the chart so the Redis PVC binds instead of staying pending
- disables Redis TLS for the in-cluster Redis chart deployment to match the chart’s bundled Redis container
- makes the dev-user bootstrap step best-effort when the OSMO user-management endpoint returns `404`, while still requiring a successful `osmo login` and applying the service configuration

This PR is intentionally scoped to deployment automation and setup manifests. It does not change Terraform resource provisioning or the upstream OSMO Helm chart.

Validation performed:

- `bash -n infrastructure/setup/03-deploy-osmo-control-plane.sh shared/lib/common.sh`
- rendered `osmo/service` locally with sanitized values to verify `services.redis.storageClassName`, `services.redis.tlsEnabled`, and `redis-secret` handling
- re-ran the sanitized deployment flow:

```bash
cd infrastructure/terraform
terraform init
terraform apply -var-file=<sanitized>.tfvars

cd ../setup
./03-deploy-osmo-control-plane.sh --use-incluster-redis
kubectl get pods -n osmo-control-plane
helm list -n osmo-control-plane
```

- confirmed `service`, `router`, and `ui` Helm releases reached `deployed`
- confirmed `osmo-agent`, `osmo-delayed-job-monitor`, `osmo-logger`, `osmo-router`, `osmo-service`, `osmo-ui`, `osmo-worker`, and `redis` were `Running`

Side-effect review:

- `shared/lib/common.sh` is shared through symlinks into both `infrastructure/setup` and `data-management/setup`
- the new SecretProviderClass argument only affects the OSMO control-plane deploy caller
- `osmo_login_and_setup` is also used by the OSMO backend deploy script; the change only converts optional dev-user setup into a warning when the endpoint is unavailable
- the uninstall script already cleans up `redis-secret`, so the new in-cluster secret does not add cleanup drift

Closes #316 

## Type Of Change

- [x] 🐛 Bug fix (non-breaking change fixing an issue)
- [ ] ✨ New feature (non-breaking change adding functionality)
- [ ] 💥 Breaking change (fix or feature causing existing functionality to change)
- [ ] 📚 Documentation update
- [ ] 🏗️ Infrastructure change (Terraform/IaC)
- [x] ♻️ Refactoring (no functional changes outside the deploy fix)

## Component(s) Affected

- [ ] `infrastructure/terraform/prerequisites/` - Azure subscription setup
- [ ] `infrastructure/terraform/` - Terraform infrastructure
- [x] `infrastructure/setup/` - OSMO control plane / Helm
- [ ] `workflows/` - Training and evaluation workflows
- [ ] `training/` - Training pipelines and scripts
- [ ] `docs/` - Documentation

## Testing Performed

- [ ] Terraform `plan` reviewed (no unexpected changes)
- [x] Terraform `apply` tested in a sanitized dev configuration
- [ ] Training scripts tested locally with Isaac Sim
- [ ] OSMO workflow submitted successfully
- [ ] Smoke tests passed (`smoke_test_azure.py`)

## Documentation Impact

- [x] No documentation changes needed
- [ ] Documentation updated in this PR
- [ ] Documentation issue filed

## Bug Fix Checklist

- [ ] Linked to issue being fixed
- [ ] Regression test included, OR
- [x] Justification for no regression test: this repository’s deploy automation is validated through script checks, chart rendering, and live environment deploy verification rather than an automated integration test for AKS + Helm + workload identity + OSMO.

## Checklist

- [x] My code follows the project conventions
- [ ] Commit messages follow conventional commit format
- [x] I have performed a self-review
- [x] Documentation impact assessed above
- [x] No new linting warnings introduced that are attributable to this change

### CODE REVIEW

File: shared/lib/common.sh [hunk 1]
```diff
@@ -239,28 +252,32 @@ osmo_login_and_setup() {
   osmo login "${service_url}/" --method dev --username "$username"
   info "Ensuring dev user '$username' exists with $roles role..."
   if ! osmo user get "$username" &>/dev/null; then
-    osmo user create "$username" --roles "$roles"
+    osmo user create "$username" --roles "$roles" >/dev/null 2>&1 || warn "OSMO user management endpoint unavailable; skipping dev user setup"
   else
-    osmo user update "$username" --add-roles "$roles"
+    osmo user update "$username" --add-roles "$roles" >/dev/null 2>&1 || warn "Unable to update OSMO dev user roles; continuing"
   fi
```
Comment (katriendg) [inline shared/lib/common.sh:266]: The user-management commands now swallow all failures (`>/dev/null 2>&1 || warn ...`), not just the 404 that motivated the change. This also affects `04-deploy-osmo-backend.sh` which calls the same function. Network errors, auth failures, and misconfiguration will all be silently downgraded to warnings with no diagnostic output.

**Suggested change:**

```bash
if ! osmo user get "$username" &>/dev/null; then
  osmo user create "$username" --roles "$roles" 2>&1 || warn "OSMO user management endpoint unavailable; skipping dev user setup"
else
  osmo user update "$username" --add-roles "$roles" 2>&1 || warn "Unable to update OSMO dev user roles; continuing"
fi
```

At minimum, keep stderr visible so the operator can see what failed before the warning. Ideally, check for a specific 404 status rather than swallowing all errors.

File: shared/lib/common.sh [hunk 2]
```diff
@@ -239,28 +252,32 @@ osmo_login_and_setup() {
...
 apply_secret_provider_class() {
   local namespace="${1:?namespace required}"
   local keyvault="${2:?keyvault name required}"
   local client_id="${3:?client_id required}"
   local tenant_id="${4:?tenant_id required}"
+  local include_redis_secret="${5:-true}"
 
   local manifest_dir
-  manifest_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)/infrastructure/setup/manifests"
+  manifest_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/manifests"
```
Comment (katriendg) [inline shared/lib/common.sh:280]: 💡 The path change from `../../` to `..` fixes the broken resolution when `BASH_SOURCE[0]` follows the symlink path (`infrastructure/setup/lib/common.sh` → `shared/lib/common.sh`). This works because bash consistently preserves the symlink path in `BASH_SOURCE`. Worth a brief inline comment noting this expectation, since the function lives in `shared/lib/` but resolves paths relative to its symlinked location.

File: shared/lib/common.sh [hunk 3]
```diff
@@ -163,6 +163,19 @@ detect_service_url() {
...
+
+  storage_class=$(kubectl get storageclass -o jsonpath='{range .items[?(@.metadata.annotations.storageclass\.kubernetes\.io/is-default-class=="true")]}{.metadata.name}{"\n"}{end}' 2>/dev/null | head -n 1)
+
+  if [[ -z "$storage_class" ]]; then
+    storage_class=$(kubectl get storageclass default -o jsonpath='{.metadata.name}' 2>/dev/null || true)
+  fi
+
+  [[ -n "$storage_class" ]] || fatal "No default StorageClass detected for in-cluster Redis"
+  echo "$storage_class"
+}
```
Comment (katriendg) [inline shared/lib/common.sh:177]: 💡 The annotation-based lookup is the correct primary approach. The fallback to a literal `storageclass default` name is unlikely to trigger on AKS (default classes are named `managed-csi` or `managed-csi-premium`), but it's a harmless safety net. The `fatal` exit on complete failure is appropriate.

File: infrastructure/setup/03-deploy-osmo-control-plane.sh [hunk 4]
```diff
@@ -206,7 +207,7 @@ fi
 
 if [[ -n "$osmo_identity_client_id" ]]; then
   info "Applying SecretProviderClass for Azure Key Vault CSI driver..."
-  apply_secret_provider_class "$NS_OSMO_CONTROL_PLANE" "$keyvault" "$osmo_identity_client_id" "$tenant_id"
+  apply_secret_provider_class "$NS_OSMO_CONTROL_PLANE" "$keyvault" "$osmo_identity_client_id" "$tenant_id" "$([[ "$use_incluster_redis" == "false" ]] && echo true || echo false)"
```
Comment (katriendg) [inline infrastructure/setup/03-deploy-osmo-control-plane.sh]: 💡 The double-negation ("if NOT in-cluster, then include redis is true") is hard to parse at a glance. Consider extracting to a variable:

```bash
include_redis_secret=$([[ "$use_incluster_redis" == "false" ]] && echo true || echo false)
apply_secret_provider_class "$NS_OSMO_CONTROL_PLANE" "$keyvault" "$osmo_identity_client_id" "$tenant_id" "$include_redis_secret"
```

File: infrastructure/setup/03-deploy-osmo-control-plane.sh [hunk 5]
```diff
@@ -227,6 +228,15 @@ else
   fi
 fi
 
+if [[ "$use_incluster_redis" == "true" ]]; then
+  redis_storage_class=$(detect_default_storage_class)
+  info "Creating Redis secret for in-cluster Redis..."
+  kubectl create secret generic "$SECRET_REDIS" \
+    --namespace="$NS_OSMO_CONTROL_PLANE" \
+    --from-literal=redis-password="" \
+    --dry-run=client -o yaml | kubectl apply -f -
```
Comment (katriendg) [inline infrastructure/setup/03-deploy-osmo-control-plane.sh:241]: The in-cluster Redis path creates a secret with an empty password and disables TLS. This is expected for the chart's bundled Redis container, but it means the Redis instance has no authentication or encryption in transit. For dev/test this is fine. If `--use-incluster-redis` is ever used in production, this becomes a security gap.

Consider adding a brief note in the `--help` text for `--use-incluster-redis` (e.g., "Uses an unauthenticated, non-TLS Redis instance suitable for development environments").

File: infrastructure/setup/03-deploy-osmo-control-plane.sh [hunk 6]
```diff
@@ -60,6 +60,7 @@ use_local_osmo=false
 config_preview=false
 chart_version_set=false
 image_version_set=false
+redis_storage_class=""
```
Comment (katriendg) [inline infrastructure/setup/03-deploy-osmo-control-plane.sh]: 💡 `redis_storage_class` isn't populated until after config-preview exits. The preview shows "in-cluster" for Redis mode but can't confirm a suitable StorageClass exists. Moving the `detect_default_storage_class` call before the preview block (when `use_incluster_redis` is true) would close this gap, or the preview can note "storage class: resolved at deploy time".

File: infrastructure/setup/manifests/aks-secret-provider-class-external-redis.yaml [hunk 7]
```diff
@@ -0,0 +1,42 @@
...
+    - secretName: db-secret
+      type: Opaque
+      data:
+        - objectName: psql-admin-password
+          key: db-password
+    - secretName: redis-secret
+      type: Opaque
+      data:
+        - objectName: redis-primary-key
+          key: redis-password
```
Comment (katriendg) [inline infrastructure/setup/manifests/aks-secret-provider-class-external-redis.yaml:42]: 💡 The new manifest is the old unified manifest verbatim. The base manifest now has the redis section removed. This means ~80% shared content across two files. Any change to the postgres secret sync or CSI driver config needs updating in both.

Not blocking — the current approach is straightforward and reduces script complexity vs. template manipulation. Just noting the maintenance trade-off.

**Review by katriendg — CHANGES_REQUESTED** [review]
Good work — the PR correctly addresses all five failure modes from #316. Code follows codebase conventions (idempotent kubectl, `--dry-run=client` pattern, `set -o errexit -o nounset`), passes `bash -n` and `shellcheck` cleanly, and the live deploy validation is solid.

**One requested change:** Address the error-swallowing in `osmo_login_and_setup` (see inline comment on `shared/lib/common.sh` L255–258). At minimum, remove `>/dev/null` so stderr is visible to operators. The remaining inline comments are non-blocking suggestions.

**What looks good:**
- Idempotent secret creation via `--dry-run=client -o yaml | kubectl apply -f -`
- Correct use of `--set-string` for `storageClassName` (prevents Helm type coercion)
- `tf_get` (soft) for optional redis outputs vs `tf_require` for required values
- Annotation-based StorageClass detection with `fatal` fallback
- No cleanup drift — uninstall script already handles `redis-secret`

File: shared/lib/common.sh (hunk 1 above)
Comment (fbeltrao) [reply shared/lib/common.sh:266]: Updated `osmo_login_and_setup` so it only creates the dev user when the lookup fails with a 404-style response. Other lookup failures now keep the CLI diagnostics visible and skip user setup instead of being silently downgraded to a warning.



When user does not exists it returns:
`Server responded with status code 400 Error message: User guest1 not found Error code: 400`

File: shared/lib/common.sh (hunk 2 above)
Comment (fbeltrao) [reply shared/lib/common.sh:280]: Added a brief inline comment in `apply_secret_provider_class` explaining that `BASH_SOURCE[0]` preserves the symlinked `infrastructure/setup/lib` path, so `../manifests` resolves from the setup directory as intended.

File: shared/lib/common.sh (hunk 3 above)
Comment (fbeltrao) [reply shared/lib/common.sh:177]: Ok if I leave as-is?

File: infrastructure/setup/03-deploy-osmo-control-plane.sh (hunk 4 above)
Comment (fbeltrao) [reply infrastructure/setup/03-deploy-osmo-control-plane.sh]: Extracted the `include_redis_secret` flag before calling `apply_secret_provider_class` so the external Redis condition reads directly.

File: infrastructure/setup/03-deploy-osmo-control-plane.sh (hunk 5 above)
Comment (fbeltrao) [reply infrastructure/setup/03-deploy-osmo-control-plane.sh:241]: Added the development-only security note to `--use-incluster-redis` help text and a runtime warning before creating the in-cluster Redis secret.

File: infrastructure/setup/03-deploy-osmo-control-plane.sh (hunk 6 above)
Comment (fbeltrao) [reply infrastructure/setup/03-deploy-osmo-control-plane.sh]: We need to select between
a) Displaying the redis_storage_class during a `--config-preview`. Pros: it validates the storage class for in cluster Redis. Cons: complexity; adding a new reasons for the script to fail (not being able to connect to cluster)
b) Do not display `redis_storage_class` during a `--config-preview`. Pros: code is simpler; not fails if cluster connection is not available. Cons: we don't display resolved storage class.

I have implemented a), happy to change if the added complexity is worth it.

File: infrastructure/setup/manifests/aks-secret-provider-class-external-redis.yaml (hunk 7 above)
Comment (fbeltrao) [reply infrastructure/setup/manifests/aks-secret-provider-class-external-redis.yaml:42]: @katriendg, would you suggest us templating the file (or other solution), or leave as is for now?

Comment (katriendg) [reply infrastructure/setup/manifests/aks-secret-provider-class-external-redis.yaml:42]: I believe we can leave as-is, not a huge thing.

File: shared/lib/common.sh (hunk 3 above)
Comment (katriendg) [reply shared/lib/common.sh:177]: Totally

File: infrastructure/setup/03-deploy-osmo-control-plane.sh (hunk 6 above)
Comment (katriendg) [reply infrastructure/setup/03-deploy-osmo-control-plane.sh]: LGTM

**Review by katriendg — APPROVED** [review]
Thanks for the updates, looks good to merge.
